package com.revature.Objects;

import java.util.Objects;

public class Offer {
	@Override
	public int hashCode() {
		return Objects.hash(accepted, carId, customerId, offerAmount, offerId);
	}
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Offer other = (Offer) obj;
		return accepted == other.accepted && carId == other.carId && customerId == other.customerId
				&& Objects.equals(offerAmount, other.offerAmount) && offerId == other.offerId;
	}
	private int offerId;
	private int customerId;
	private int carId;
	private Double offerAmount;
	private boolean accepted;
	
	
	public int getOfferId() {
		return offerId;
	}
	public void setOfferId(int offerId) {
		this.offerId = offerId;
	}
	public Double getOfferAmount() {
		return offerAmount;
	}
	public void setOfferAmount(Double offerAmount) {
		this.offerAmount = offerAmount;
	}
	public boolean isAccepted() {
		return accepted;
	}
	public void setAccepted(boolean accepted) {
		this.accepted = accepted;
	}
	
	//Add offer constructor, offerId generated by DB
		public Offer(int customerId, int carId, Double offerAmount, boolean accepted) {
			super();
			this.customerId = customerId;
			this.carId = carId;
			this.offerAmount = offerAmount;
			this.accepted = false;
		}
		
		//Read offer constructor
		public void ReadOffer(int customerId, int carId, Double offerAmount, boolean accepted) {
			this.customerId = customerId;
			this.carId = carId;
			this.offerAmount = offerAmount;
			this.accepted = accepted;
		}
		public int getCustomerId() {
			return customerId;
		}
		public void setCustomerId(int customerId) {
			this.customerId = customerId;
		}
		public int getCarId() {
			return carId;
		}
		public void setCarId(int carId) {
			this.carId = carId;
		}
}
